server:
  port: 9090
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512
  max-http-request-header-size: 48000
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2000MB
      max-request-size: 2150MB
  cloud:
    gcp:
      config:
        project-id: hip-field-428707-f0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_URL}
    username: postgres
#    password: root
    password: Bilge*!
  jpa:
    hibernate:
      ddl-auto: update

